api:
  url-base: ${API_URL_BASE:https://api.github.com/repos}
github:
  token: ${GITHUB_TOKEN:token123}

management:
  server:
    port: 9075
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
  endpoint:
    prometheus:
      access: unrestricted

# Security
security:
  # SSL
  tls:
    enabled: false
    keystores: []
