http-server:
  host: "0.0.0.0"
  port: 8080
api:
  url-base: ${API_URL_BASE:https://api.github.com/repos}
github:
  token: ${GITHUB_TOKEN:token123}
security:
  ssl:
    enable: true
    keystores:
      - path: svc_wiremock.jks
        password: password
  ssh:
    enabled: ${SECURITY_SSH_ENABLED:false}
    public-key: classpath:keys/id_client.pub
    private-key: classpath:keys/id_client
