/*
 * This source file was generated by the Gradle 'init' task
 */
package org.hali;

import lombok.RequiredArgsConstructor;
import lombok.extern.log4j.Log4j2;
import org.hali.security.TrustStoreProperties;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.core.env.Environment;

@Log4j2
@SpringBootApplication
@RequiredArgsConstructor
public class HaliApplication implements CommandLineRunner {

    private final TrustStoreProperties trustStoreProperties;
    private final Environment environment;

    public static void main(String[] args) {
        SpringApplication.run(HaliApplication.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        final String port = this.environment.getProperty("server.port");
        final String address = this.environment.getProperty("server.address", "localhost");

        log.info("Application running on {}:{}", address, port);
    }
}
