integration:
  # API
  api:
    url-base: overrideMe

  # Git
  git-server:
    dir-path: git/kibonga-upstream
    repo:
      name: kibonga-upstream.git
      branch: master

  # Wiremock
  wiremock:
    mappings:
      host: wiremock/mappings
      container: /home/wiremock/mappings
    keystore:
      path: wiremock/keystore/svc_wiremock.jks
      password: password

    # SSH
    ssh:
      dir-path: keys
      keys:
        private-key: id_client
        public-key: id_client.pub

# Security
security:
  # SSL
  tls:
    enabled: true
    keystores:
      - path: wiremock/keystore/svc_wiremock.jks
        password: password
